<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable PHPCompatibility.Miscellaneous.RemovedAlternativePHPTags.MaybeASPOpenTagFound
/** @var $block \Scaleflex\FileRobot\Block\Adminhtml\Product\Helper\Form\Gallery\Content */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
$elementName = $block->getElement()->getName() . '[images]';
$formName = $block->getFormName();
/** @var \Magento\Framework\Json\Helper\Data $jsonHelper */
$jsonHelper = $block->getData('jsonHelper');
?>

<div id="<?= $block->getHtmlId() ?>"
     class="gallery"
     data-mage-init='{"productGallery":{"template":"#<?= $block->getHtmlId() ?>-template"}}'
     data-parent-component="<?= $block->escapeHtml($block->getData('config/parentComponent')) ?>"
     data-images="<?= $block->escapeHtml($block->getImagesJson()) ?>"
     data-types="<?= $block->escapeHtml($jsonHelper->jsonEncode($block->getImageTypes())) ?>"
>
    <?php if (!$block->getElement()->getReadonly()) {?>
        <div id="filerobot-file-manager">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
            <span>Image Manager</span>
        </div>
        <div id="filerobot-modal-content">
            <div id="filerobot-fmaw"></div>
        </div>
    <?php } ?>
    <?php foreach ($block->getImageTypes() as $typeData) {
        ?>
        <input name="<?= $block->escapeHtmlAttr($typeData['name']) ?>"
               data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
               class="image-<?= $block->escapeHtmlAttr($typeData['code']) ?>"
               type="hidden"
               value="<?= $block->escapeHtmlAttr($typeData['value']) ?>"/>
        <?php
    } ?>

    <script id="<?= $block->getHtmlId() ?>-template" type="text/x-magento-template">
        <div class="image item<% if (data.disabled == 1) { %> hidden-for-front<% } %>"
             data-role="image">
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][position]"
                   value="<%- data.position %>"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   class="position"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][file]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value="<%- data.file %>"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][value_id]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value="<%- data.value_id %>"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][label]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value="<%- data.label %>"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][disabled]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value="<%- data.disabled %>"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][media_type]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value="image"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][removed]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value=""
                   class="is-removed"/>

            <div class="product-image-wrapper">
                <img class="product-image"
                     data-role="image-element"
                     src="<%- data.url %>"
                     alt="<%- data.label %>"/>

                <div class="actions">
                    <button type="button"
                            class="action-remove"
                            data-role="delete-button"
                            title="<?= $block->escapeHtmlAttr(__('Delete image')) ?>">
                    <span>
                        <?= $block->escapeHtml(__('Delete image')) ?>
                    </span>
                    </button>
                    <div class="draggable-handle"></div>
                </div>
                <div class="image-fade"><span><?= $block->escapeHtml(__('Hidden')) ?></span></div>
            </div>


            <div class="item-description">
                <div class="item-title" data-role="img-title"><%- data.label %></div>
                <div class="item-size">
                    <span data-role="image-dimens"></span>, <span data-role="image-size"><%- data.sizeLabel %></span>
                </div>
            </div>

            <ul class="item-roles" data-role="roles-labels">
                <?php
                foreach ($block->getImageTypes() as $typeData) {
                    ?>
                    <li data-role-code="<?= $block->escapeHtmlAttr($typeData['code']) ?>"
                        class="item-role item-role-<?= $block->escapeHtmlAttr($typeData['code']) ?>">
                        <?= $block->escapeHtml($typeData['label']) ?>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
    </script>

    <script data-role="img-dialog-container-tmpl" type="text/x-magento-template">
        <div class="image-panel" data-role="dialog">
        </div>
    </script>

    <script data-role="img-dialog-tmpl" type="text/x-magento-template">
        <div class="image-panel-preview">
            <img src="<%- data.url %>" alt="<%- data.label %>" />
        </div>
        <div class="image-panel-controls">
            <strong class="image-name"><%- data.label %></strong>

            <fieldset class="admin__fieldset fieldset-image-panel">
                <div class="admin__field field-image-description">
                    <label class="admin__field-label" for="image-description">
                        <span><?= $block->escapeHtml(__('Alt Text')) ?></span>
                    </label>

                    <div class="admin__field-control">
                            <textarea data-role="image-description"
                                      rows="3"
                                      class="admin__control-textarea"
                                      name="<?= $block->escapeHtmlAttr($elementName)
                                      ?>[<%- data.file_id %>][label]"><%- data.label %>
                            </textarea>
                    </div>
                </div>

                <div class="admin__field field-image-role">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Role')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <ul class="multiselect-alt">
                            <?php
                            foreach ($block->getMediaAttributes() as $attribute):
                                ?>
                                <li class="item">
                                    <label>
                                        <input class="image-type"
                                               data-role="type-selector"
                                               data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                                               type="checkbox"
                                               value="<?= $block->escapeHtmlAttr($attribute->getAttributeCode()) ?>"
                                        />
                                        <?= $block->escapeHtml(
                                            $attribute->getFrontendLabel()
                                        ) ?>
                                    </label>
                                </li>
                            <?php
                            endforeach;
                            ?>
                        </ul>
                    </div>
                </div>

                <div class="admin__field admin__field-inline field-image-size" data-role="size">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Image Size')) ?></span>
                    </label>
                    <div class="admin__field-value" data-message="<?= $block->escapeHtmlAttr(__('{size}')) ?>"></div>
                </div>

                <div class="admin__field admin__field-inline field-image-resolution" data-role="resolution">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Image Resolution')) ?></span>
                    </label>
                    <div class="admin__field-value"
                         data-message="<?= $block->escapeHtmlAttr(__('{width}^{height} px')) ?>"></div>
                </div>

                <div class="admin__field field-image-hide">
                    <div class="admin__field-control">
                        <div class="admin__field admin__field-option">
                            <input type="checkbox"
                                   id="hide-from-product-page"
                                   data-role="visibility-trigger"
                                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                                   value="1"
                                   class="admin__control-checkbox"
                                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][disabled]"
                            <% if (data.disabled == 1) { %>checked="checked"<% } %> />

                            <label for="hide-from-product-page" class="admin__field-label">
                                <?= $block->escapeHtml(__('Hide from Product Page')) ?>
                            </label>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </script>
    <?= $block->getChildHtml('new-video') ?>
</div>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], "jQuery('body').trigger('contentUpdated');", false) ?>
<script type="text/javascript">
    require(["jquery", "Magento_Ui/js/modal/modal"], function (jQuery, modal) {
        const container  = '<?php echo $block->getConfig()->getToken(); ?>';
        const templateId = '<?php echo $block->getConfig()->getTemplateId(); ?>';
        const uploadDir  = '<?php echo $block->getConfig()->getUploadDir(); ?>';

        var options = {
            type: 'popup',
            responsive: true,
            title: '',
            buttons: []
        };

        const Filerobot = window.Filerobot;


        var popup = modal(options, jQuery('#filerobot-modal-content'));

        const filerobot = Filerobot.Core({
            securityTemplateID: templateId,
            container: container
        });

        const Explorer = Filerobot.Explorer;
        const XHRUpload = Filerobot.XHRUpload;
        const ImageEditor = Filerobot.ImageEditor;
        const Webcam = Filerobot.Webcam;

        if (container && templateId) {
            filerobot
                .use(Explorer, {
                    config: {
                        rootFolderPath: uploadDir ?? '/'
                    },
                    target: '#filerobot-fmaw',
                    inline: true,
                    width: '100%',
                    height: 530,
                    showDetailsView: true,
                    locale: {
                        strings: {
                            export: 'Insert'
                        }
                    },
                })
                .use(XHRUpload)
                .use(ImageEditor, {
                    cloudimageToken: templateId
                })
                .use(Webcam)
                .on('export', function (files, popupExportSuccessMsgFn, downloadFilesPackagedFn, downloadFileFn) {
                    files.forEach((selected, key) => {

                        let link = selected.link;

                        if (!link.includes('width=')) {
                            link += ('&width=' + selected.file.info.img_w);
                        }

                        if (!link.includes('height=')) {
                            link += ('&height=' + selected.file.info.img_h);
                        }

                        const url = link + '&size=' + selected.file.size.bytes;
                        const imageData = {
                            error: 0,
                            file: url,
                            name: selected.file.name,
                            size: selected.file.size.bytes,
                            type: selected.file.type,
                            url: url

                        };
                        jQuery('#media_gallery_content').trigger('addItem', imageData);
                    })
                    jQuery('#filerobot-modal-content').modal('closeModal')
                    files = []
                    return false
                });
        }

        jQuery("#filerobot-file-manager").click(function () {
            jQuery('#filerobot-modal-content').modal('openModal');
        });
    });
</script>
<style>
    #filerobot-file-manager {
        display: inline-block;
        border: 1px solid lightgrey;
        margin-top: 12px;
        width: 150px;
        height: 150px;
        cursor: pointer;
    }

    #filerobot-file-manager:hover span,
    #filerobot-file-manager:hover svg{
        color: #0a6c9f;
    }

    #filerobot-file-manager svg {
        width: 50px;
        height: 50px;
        display: block;
        margin: 30px auto 6px;
        color: lightgrey;
    }

    #filerobot-file-manager span {
        text-align: center;
        display: block;
        font-size: 14px;
        padding: 11px;
    }
</style>
