<?php
/** @var \Scaleflex\Filerobot\Block\Adminhtml\Firerobot $block */
?>
<link rel="stylesheet" type="text/css"
      href="https://scaleflex.cloudimg.io/v7/plugins/filerobot-widget/v3/stable/filerobot-widget.min.css"/>

<button style="display: none" id="filerobot-modal-btn"></button>
<div id="filerobot-widget"></div>

<script type="text/javascript">
    require.config({
        paths: {
            filerobot: 'https://scaleflex.cloudimg.io/v7/plugins/filerobot-widget/v3/stable/filerobot-widget.min'
        }
    });
    require(["jquery", "filerobot"], function (jQuery, modal, filerobot, _) {
        const container = '<?php echo $block->getConfig()->getToken(); ?>';
        const templateId = '<?php echo $block->getConfig()->getTemplateId(); ?>';
        const uploadDir = '<?php echo $block->getConfig()->getUploadDir(); ?>';

        const Filerobot = window.Filerobot;
        if (container && templateId) {
            const filerobot = Filerobot.Core({
                securityTemplateID: templateId,
                container: container
            });

            const Explorer = Filerobot.Explorer;
            const XHRUpload = Filerobot.XHRUpload;

            filerobot
                .use(Explorer, {
                    config: {
                        rootFolderPath: uploadDir ?? '/'
                    },
                    target: '#filerobot-widget',
                    inline: false,
                    trigger: '#filerobot-modal-btn',
                    showFoldersTree: false,
                    preventDownloadDefaultBehavior: true,
                    filters: {
                        mimeTypes: ['image'],
                    },
                    locale: {
                        strings: {
                            mutualizedExportButtonLabel: 'Insert',
                            mutualizedDownloadButton: 'Insert',
                        }
                    },
                })
                .use(XHRUpload)
                .on('export', function (files, popupExportSuccessMsgFn, downloadFilesPackagedFn, downloadFileFn) {
                    window.fr_files = files;

                    files.forEach((selected, key) => {
                        let link = new URL(selected.file.url.cdn);
                        let width = selected.file.info.img_w;
                        let height = selected.file.info.img_h;
                        let crop = false;


                        if ('download' in selected.file.url) {
                            link = new URL(selected.file.url.download);
                        }
                        let params = new URLSearchParams(link.search);

                        if (params.has('width') && params.has('height')) {
                            width = params.get('width');
                            height = params.get('height');
                        }

                        if (params.has('tl_px')) {
                            crop = true;
                        }

                        if (crop === false) {
                            if (!params.has('width')) {
                                link += ('&width=' + width);
                            }

                            if (!params.has('height')) {
                                link += ('&height=' + height);
                            }

                            const img = '<div>' +
                                '<img src="' + link + '" ' +
                                ' width="' + width + '"' +
                                ' height="' + height + '"' +
                                ' alt="' + selected.file.meta.title + '" /> ' +
                                '</div>'

                            window.fileRobotActiveEditor.execCommand('mceInsertContent', false, img);
                        } else {
                            const img = '<div>' +
                                '<img src="' + link + '" ' +
                                ' alt="' + selected.file.meta.title + '" /> ' +
                                '</div>'

                            window.fileRobotActiveEditor.execCommand('mceInsertContent', false, img);
                        }
                    })
                    window.fileRobotActiveEditor = undefined
                    return false
                });
        }
    });
</script>

<style>
    .modal-popup .modal-inner-wrap{
        min-height: 650px;
    }
    .filerobot-Explorer-inner {
        max-width: 100%!important;
        max-height: 100%!important;
    }
    .filerobot-u-reset{
        top: 0!important;
    }

    button.filerobot-u-reset.filerobot-Explorer-close {
        border: 2px solid #efe2e2;
        border-radius: 50px;
        width: 24px;
        height: 24px;
        display: flex;
        justify-content: center;
        background: white;
    }

    button.filerobot-u-reset.filerobot-Explorer-close span {
        font-size: 19px;
        color: tomato;
        transition-delay: 500s;
    }

    button.filerobot-u-reset.filerobot-Explorer-close:hover {
        border-color: tomato;
    }
</style>
