<?php
/** @var \Scaleflex\Filerobot\Block\Adminhtml\Firerobot $block */
?>
<link rel="stylesheet" type="text/css"
      href="https://scaleflex.cloudimg.io/v7/plugins/filerobot-widget/v3/stable/filerobot-widget.min.css"/>

<button style="display: none" id="filerobot-modal-btn"></button>
<div id="filerobot-widget"></div>

<script type="text/javascript">
    require.config({
        paths: {
            filerobot: 'https://scaleflex.cloudimg.io/v7/plugins/filerobot-widget/v3/stable/filerobot-widget.min'
        }
    });
    require(["jquery", "filerobot"], function (jQuery, modal, filerobot, _) {
        const container = '<?php echo $block->getConfig()->getToken(); ?>';
        const templateId = '<?php echo $block->getConfig()->getTemplateId(); ?>';
        const uploadDir = '<?php echo $block->getConfig()->getUploadDir(); ?>';

        const Filerobot = window.Filerobot;
        if (container && templateId) {
            const filerobot = Filerobot.Core({
                securityTemplateID: templateId,
                container: container
            });

            const Explorer = Filerobot.Explorer;
            const XHRUpload = Filerobot.XHRUpload;

            filerobot
                .use(Explorer, {
                    config: {
                        rootFolderPath: uploadDir ?? '/'
                    },
                    target: '#filerobot-widget',
                    inline: false,
                    trigger: '#filerobot-modal-btn',
                    showFoldersTree: false,
                    preventDownloadDefaultBehavior: true,
                    locale: {
                        strings: {
                            mutualizedExportButtonLabel: 'Insert',
                            mutualizedDownloadButton: 'Insert',
                        }
                    },
                })
                .use(XHRUpload)
                .on('export', function (files, popupExportSuccessMsgFn, downloadFilesPackagedFn, downloadFileFn) {
                    files.forEach((selected, key) => {
                        console.log(selected)
                        let link = selected.file.url.cdn;
                        let download = false;
                        let url = new URL(link);
                        let width = selected.file.info.img_w;
                        let height = selected.file.info.img_h;

                        if ('download' in selected.file.url) {
                            const download_link = new URL(selected.file.url.download)
                            let params = new URLSearchParams(download_link.search);

                            width = params.get('width');
                            height = params.get('height');
                        }


                        if (!link.includes('width=')) {
                            link += ('&width=' + width);
                        } else {
                            width = url.searchParams.get("width");
                        }

                        if (!link.includes('height=')) {
                            link += ('&height=' + height);
                        } else {
                            height = url.searchParams.get("height");
                        }

                        window.fileRobotActiveEditor.execCommand('mceInsertContent', false, '<div>' +
                            '<img src="' + link + '" ' +
                            ' width="' + width + '"' +
                            ' height="' + height + '"' +
                            ' alt="' + selected.file.meta.title + '" /> ' +
                            '</div>');
                    })
                    window.fileRobotActiveEditor = undefined
                    jQuery('#modal-content').modal('closeModal')
                    files = []
                    return false
                });
        }
    });
</script>

<style>
    .modal-popup .modal-inner-wrap{
        min-height: 650px;
    }
    .filerobot-Explorer-inner {
        max-width: 100%!important;
        max-height: 100%!important;
    }
    .filerobot-u-reset{
        top: 0!important;
    }

    button.filerobot-u-reset.filerobot-Explorer-close {
        border: 2px solid #efe2e2;
        border-radius: 50px;
        width: 24px;
        height: 24px;
        display: flex;
        justify-content: center;
        background: white;
    }

    button.filerobot-u-reset.filerobot-Explorer-close span {
        font-size: 19px;
        color: tomato;
    }
</style>
